<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yuan</groupId>
        <artifactId>daydayup-common</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>daydayup-common-mq</artifactId>
    <description>RocketMQ 生产者 / 消费者抽象、事务消息模板</description>

    <dependencies>
        <dependency>
            <groupId>com.yuan</groupId>
            <artifactId>daydayup-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>
