<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yuan</groupId>
        <artifactId>daydayup-common</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>daydayup-common-xxljob</artifactId>
    <description>XXL-JOB 执行器自动装配</description>

    <dependencies>
        <dependency>
            <groupId>com.yuan</groupId>
            <artifactId>daydayup-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>
