-- DayDayUP Reading initialization DDL
-- Target database: daydayup_reading
-- BaseEntity convention: id, create_time, update_time, create_by, update_by, deleted.

CREATE TABLE IF NOT EXISTS reading_source_definition (
    id BIGINT NOT NULL COMMENT '雪花主键',
    name VARCHAR(128) NOT NULL COMMENT '书源名称',
    site_name VARCHAR(128) NULL COMMENT '站点/分组',
    book_source_url VARCHAR(512) NOT NULL COMMENT '书源基准 URL / 幂等键',
    book_source_type TINYINT NOT NULL DEFAULT 0 COMMENT '类型：0文字 1听书 2漫画',
    origin_type VARCHAR(32) NOT NULL DEFAULT 'legado' COMMENT '来源格式：legado/custom 等',
    origin_path VARCHAR(512) NULL COMMENT '导入来源路径',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '启用状态：0禁用 1启用',
    priority INT NOT NULL DEFAULT 0 COMMENT '优先级/权重',
    tags VARCHAR(512) NULL COMMENT '标签，逗号分隔',
    compile_grade VARCHAR(32) NULL COMMENT '最近编译等级：full/degraded/rejected',
    fingerprint CHAR(64) NOT NULL COMMENT '原始规则 SHA-256 指纹',
    imported_at DATETIME NULL COMMENT '最近导入时间',
    raw_content LONGTEXT NOT NULL COMMENT '脱敏后的原始书源 JSON',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_source_definition_url (book_source_url),
    KEY idx_reading_source_definition_status (status, deleted, priority),
    KEY idx_reading_source_definition_type (book_source_type, deleted),
    KEY idx_reading_source_definition_compile (compile_grade, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读书源定义';

CREATE TABLE IF NOT EXISTS reading_source_compiled_rule (
    id BIGINT NOT NULL COMMENT '雪花主键',
    source_id BIGINT NOT NULL COMMENT '书源 ID',
    compiler_version VARCHAR(32) NOT NULL COMMENT '编译器版本',
    dsl_schema_version VARCHAR(32) NOT NULL COMMENT 'RuleModel schema 版本',
    compile_status VARCHAR(32) NOT NULL COMMENT '编译等级：full/degraded/rejected',
    compile_warnings JSON NULL COMMENT '编译警告 JSON 数组',
    script_deps JSON NULL COMMENT '脚本依赖 JSON 数组',
    compiled_content LONGTEXT NOT NULL COMMENT 'RuleModel JSON 编译产物',
    compiled_at DATETIME NOT NULL COMMENT '编译时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_source_compiled_rule_source (source_id),
    KEY idx_reading_source_compiled_rule_status (compile_status, deleted),
    KEY idx_reading_source_compiled_rule_compiled_at (compiled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读书源编译产物';

CREATE TABLE IF NOT EXISTS reading_work (
    id BIGINT NOT NULL COMMENT '雪花主键',
    title VARCHAR(256) NOT NULL COMMENT '作品标题',
    author_name VARCHAR(128) NULL COMMENT '作者名',
    category_name VARCHAR(128) NULL COMMENT '分类',
    cover_url VARCHAR(1024) NULL COMMENT '封面 URL',
    description TEXT NULL COMMENT '简介',
    completion_status VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '完结状态：serial/completed/unknown',
    word_count BIGINT NULL COMMENT '字数',
    latest_chapter_title VARCHAR(256) NULL COMMENT '最新章节标题',
    latest_chapter_updated_at DATETIME NULL COMMENT '最新章节更新时间',
    aggregation_status VARCHAR(32) NOT NULL DEFAULT 'single_source' COMMENT '归并状态：single_source/merged/suspect',
    match_key VARCHAR(512) NOT NULL COMMENT '保守归并键',
    source_count INT NOT NULL DEFAULT 1 COMMENT '已绑定来源数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    KEY idx_reading_work_match (match_key, deleted),
    KEY idx_reading_work_category (category_name, completion_status, deleted),
    KEY idx_reading_work_latest (latest_chapter_updated_at, update_time, id),
    KEY idx_reading_work_title_author (title, author_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读统一作品';

CREATE TABLE IF NOT EXISTS reading_work_source_binding (
    id BIGINT NOT NULL COMMENT '雪花主键',
    work_id BIGINT NOT NULL COMMENT '统一作品 ID',
    source_id BIGINT NOT NULL COMMENT '书源 ID',
    source_book_url VARCHAR(1024) NOT NULL COMMENT '来源书籍详情 URL / 源内幂等键',
    source_book_name VARCHAR(256) NULL COMMENT '来源书名',
    source_author_name VARCHAR(128) NULL COMMENT '来源作者',
    match_confidence INT NOT NULL DEFAULT 100 COMMENT '匹配置信度 0-100',
    is_primary_source TINYINT NOT NULL DEFAULT 0 COMMENT '是否主来源：1是',
    binding_status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '绑定状态：active/unbound',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_work_source_book (source_id, source_book_url(255)),
    KEY idx_reading_work_source_binding_work (work_id, binding_status, deleted, is_primary_source),
    KEY idx_reading_work_source_binding_source (source_id, binding_status, deleted),
    KEY idx_reading_work_source_binding_primary (work_id, deleted, binding_status, is_primary_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读作品书源绑定';

CREATE TABLE IF NOT EXISTS reading_chapter (
    id BIGINT NOT NULL COMMENT '雪花主键',
    work_id BIGINT NOT NULL COMMENT '统一作品 ID',
    chapter_title VARCHAR(256) NOT NULL COMMENT '章节标题',
    chapter_index INT NOT NULL COMMENT '章节序号，从 0 起',
    volume_name VARCHAR(128) NULL COMMENT '卷名',
    is_vip_chapter TINYINT NOT NULL DEFAULT 0 COMMENT '是否 VIP 章节',
    chapter_status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '章节状态：active/removed',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_chapter_work_index (work_id, chapter_index),
    KEY idx_reading_chapter_work_status (work_id, deleted, chapter_status),
    KEY idx_reading_chapter_latest (work_id, deleted, chapter_index, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读统一章节';

CREATE TABLE IF NOT EXISTS reading_chapter_source_binding (
    id BIGINT NOT NULL COMMENT '雪花主键',
    work_id BIGINT NOT NULL COMMENT '统一作品 ID',
    source_id BIGINT NOT NULL COMMENT '书源 ID',
    chapter_id BIGINT NULL COMMENT '统一章节 ID，非主来源可空',
    source_chapter_url VARCHAR(1024) NOT NULL COMMENT '来源章节正文 URL',
    source_chapter_title VARCHAR(256) NULL COMMENT '来源章节标题',
    source_chapter_order INT NOT NULL COMMENT '来源目录内章节序',
    binding_confidence INT NOT NULL DEFAULT 100 COMMENT '对齐置信度 0-100',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_chapter_source_order (source_id, work_id, source_chapter_order),
    KEY idx_reading_chapter_source_chapter (chapter_id, source_id, deleted),
    KEY idx_reading_chapter_source_work_source (work_id, source_id, deleted),
    KEY idx_reading_chapter_source_url (source_id, source_chapter_url(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读章节书源绑定';

CREATE TABLE IF NOT EXISTS reading_chapter_content_snapshot (
    id BIGINT NOT NULL COMMENT '雪花主键',
    chapter_id BIGINT NOT NULL COMMENT '统一章节 ID',
    source_id BIGINT NOT NULL COMMENT '书源 ID',
    compiled_rule_id BIGINT NULL COMMENT '抓取所用编译产物 ID',
    raw_content LONGTEXT NULL COMMENT '原始正文',
    normalized_content LONGTEXT NULL COMMENT '标准化正文',
    sanitized_content LONGTEXT NULL COMMENT '净化正文',
    content_hash CHAR(64) NULL COMMENT 'raw 正文 SHA-256',
    content_status VARCHAR(32) NOT NULL DEFAULT 'empty' COMMENT 'raw_only/normalized/sanitized/empty',
    sanitization_pipeline_version VARCHAR(32) NULL COMMENT '净化 Pipeline 版本',
    fetched_at DATETIME NULL COMMENT '抓取时间',
    processed_at DATETIME NULL COMMENT '处理时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_chapter_content_snapshot_chapter_source (chapter_id, source_id),
    KEY idx_reading_chapter_content_snapshot_status (content_status, deleted),
    KEY idx_reading_chapter_content_snapshot_fetched (fetched_at),
    KEY idx_reading_chapter_content_snapshot_hash (content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读章节正文快照';

CREATE TABLE IF NOT EXISTS reading_content_sanitization_run (
    id BIGINT NOT NULL COMMENT '雪花主键',
    content_snapshot_id BIGINT NOT NULL COMMENT '正文快照 ID',
    pipeline_definition_version VARCHAR(32) NOT NULL COMMENT '净化 Pipeline 版本',
    pipeline_execution_trace JSON NULL COMMENT '执行 trace',
    removed_segments JSON NULL COMMENT '删除片段摘要',
    replaced_terms JSON NULL COMMENT '替换词摘要',
    quality_score INT NULL COMMENT '质量评分 0-100',
    run_status VARCHAR(32) NOT NULL COMMENT 'accepted/degraded/rejected/failed',
    run_at DATETIME NOT NULL COMMENT '运行时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    KEY idx_reading_content_sanitization_snapshot (content_snapshot_id, deleted, run_at),
    KEY idx_reading_content_sanitization_status (run_status, deleted),
    KEY idx_reading_content_sanitization_quality (quality_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读正文净化运行记录';

CREATE TABLE IF NOT EXISTS reading_task (
    id BIGINT NOT NULL COMMENT '雪花主键',
    task_type VARCHAR(64) NOT NULL COMMENT '任务类型',
    biz_key VARCHAR(512) NOT NULL COMMENT '业务幂等键',
    payload JSON NULL COMMENT '任务参数 JSON',
    task_status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/running/succeeded/failed/partial_succeeded/cancelled',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '当前重试次数',
    max_retry INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    next_run_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次可执行时间',
    locked_by VARCHAR(128) NULL COMMENT '锁持有者',
    locked_at DATETIME NULL COMMENT '锁定时间',
    error_message TEXT NULL COMMENT '错误信息',
    started_at DATETIME NULL COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '结束时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人',
    update_by BIGINT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_reading_task_type_biz (task_type, biz_key),
    KEY idx_reading_task_acquire (task_status, next_run_at, deleted),
    KEY idx_reading_task_locked (locked_by, locked_at),
    KEY idx_reading_task_type_status (task_type, task_status, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='阅读应用内任务';
