server:
  port: 9400

spring:
  application:
    name: daydayup-job
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:daydayup-common.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yaml
