<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yuan</groupId>
        <artifactId>daydayup-common</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>daydayup-common-log</artifactId>
    <description>操作日志：@OperLog 注解、异步入库或推送 RocketMQ</description>

    <dependencies>
        <dependency>
            <groupId>com.yuan</groupId>
            <artifactId>daydayup-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

</project>
